name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install NodeJS
      run: curl -sL https://deb.nodesource.com/setup_12.x && sudo -E bash - && sudo apt-get install -y nodejs 
    - name: login to docker
      uses: azure/docker-login@v1
    - name: login credentials to docker
      env:
        DOCKERHUB_USER: ${{ secrets.dockerhub_user }} 
        DOCKERHUB_PASS: ${{ secrets.dockerhub_pass }}
      with:
        login-server: markburgmans.docker.io
        username: ${{ DOCKERHUB_USER }}
        password: ${{ DOCKERHUB_PASS }}
    - name: create react app
      run: npx create-react-app react-app
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reactapp2:production
    - name: publish docker image to docker hub
      run: docker tag react-app:development markburgmans/react-app:development && docker push markburgmans/react-app:development
    
