name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: markburgmans/react-app:development
      env:
        DOCKERHUB_USER: ${{ dockerhub_user }} 
        DOCKERHUB_PASS: ${{ dockerhub_pass }}
    steps:
    - uses: actions/checkout@v2
    - name: install NodeJS
      run: curl -sL https://deb.nodesource.com/setup_12.x && sudo -E bash - && sudo apt-get install -y nodejs 
    - name: Docker login 
      uses: azure/docker-login@v1
      with:
        login-server: markburgmans.docker.io
        username: ${{ dockerhub_user }}
        password: ${{ dockerhub_pass }}
    - name: create react app
      run: npx create-react-app react-app
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reactapp2:production
    - name: publish docker image to docker hub
      run: docker tag react-app:development markburgmans/react-app:development && docker push markburgmans/react-app:development
    
